local cmd = {
  "ObsidianOpen",
  "ObsidianNew",
  "ObsidianQuickSwitch",
  "ObsidianFollowLink",
  "ObsidianBacklinks",
  "ObsidianTags",
  "ObsidianToday",
  "ObsidianYesterday",
  "ObsidianTomorrow",
  "ObsidianDailies",
  "ObsidianTemplate",
  "ObsidianSearch",
  "ObsidianLink",
  "ObsidianLinkNew",
  "ObsidianLinks",
  "ObsidianExtractNote",
  "ObsidianWorkspace",
  "ObsidianPasteImg",
  "ObsidianRename",
  "ObsidianToggleCheckbox",
  "ObsidianNewFromTemplate",
  "ObsidianTOC",
}

return cmd
